### ISSUE TITLE
What is LineSeriesProps

### ISSUE THREAD

**Issue by dmenne** [beto-rodriguez/LiveCharts2#1024]
There is a chapter:

https://lvcharts.com/docs/Maui/2.0.0-beta.700/CartesianChart.Line%20series%20props

However, I could not find any reference to LineSeriesProps in the source code.

**Comment by beto-rodriguez** [comment]
Thanks for the report, "props" is a short name for "properties", this was generated automatically, but I think that it should use the word "Properties" instead. I will keep this open as a reminder to update the docs.

**Comment by dmenne** [comment]
Thanks, I know that props is properties, but nevertheless I could not get the code to compile, because all props are marked as unknown. I then searched the code, and could not find a reference to props. Other things work, so I believe I have not forgotten to add a package. Using 2.0.0-beta.710

**Comment by beto-rodriguez** [comment]
Strange, it seems that there is something missing in the installation of the package, you can find help on how to build your first chart in the web site https://lvcharts.com/

Please let me know if the issue persists or there is something unclear in the docs to get started with the library.

**Comment by dmenne** [comment]
* Install github version. 
* Search for LineSeriesProps in *.cs and *.md 
* Nothing found
* Try the dev branch of github
* Again nada


What did I do wrong?

I have written quite a few programs using your beautiful package already, works find, but LineSeriesProps or any of the others do never resolve.

Did I miss some dependency?

**Comment by beto-rodriguez** [comment]
You can find that file [here](https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/cartesianChart/lineseries.md), that is the source of the docs.

Actually in every article in the website, you can click the "edit this article" link, at it will take you to the soruce of the article.

![image](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/a2e1d996-2420-422d-8c50-fd7d6c2e1b4b)

But that file is only necessary to build the docs of the web site, it is not necessary to use the library, all those files in the docs need to be compiled by "docr" (a private software that maybe in a future will be open source) it uses [scriban](https://github.com/scriban/scriban), that is why you see that syntax.

**Comment by dmenne** [comment]
Apologies to bother you again, but that page is not the source of 

https://lvcharts.com/docs/Maui/2.0.0-beta.700/CartesianChart.Line%20series%20props

I assume you have to force a rebuild from source for the documentation.


![explorer_NLrD7lNqjm](https://github.com/beto-rodriguez/LiveCharts2/assets/506275/50b44af8-08a8-406e-9222-e1589e55386e)

**Comment by beto-rodriguez** [comment]
> Apologies to bother you again

There is nothing to apologize!

It is the source, notice in that file it uses a "render" function:

`{{ render this "~/shared/series.md" }}`

That means to pull this file: [shared/series.md](https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/shared/series.md). That is why you see the 'Name property' section.

Then the template says:

`{{ render this "~/shared/datalabels.md" }}`,  that means to render [this file](https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/shared/datalabels.md)  and it will pass "this" as an argument, where this is the context of the article being rendered.

Again, this template is compiled by a private software (named "docr"), that is how it works, I am thinking to opensource it in a future, it helped me to build the docs automatically for all the platforms of the library in an easy way, it is an interesting tool that helped me to build specific docs for each platform.

There are no docs yet on how the docs are compiled now, mainly because "docr" requires some cleanup before opensource it.

**Comment by beto-rodriguez** [comment]
I will close this for now, please let me know if you have any other question.
