### ISSUE TITLE
LiveCharts Inside TabView Control in WinUi3

### ISSUE THREAD

**Issue by aspeculat0r** [beto-rodriguez/LiveCharts2#1044]
**Describe the bug**
Unable to see the control when it is inside the TabViewItem container.

**To Reproduce**
1. Make blank WinUi3 app
2. In the main window type following:
    <Grid>
        <TabView>
            <TabViewItem Header="Tab 1">
                <StackPanel>
                    <lvc:CartesianChart Series="{x:Bind vm.Series}" />
                </StackPanel>
            </TabViewItem>
        </TabView>
    </Grid>

**Expected behavior**
Expected to see the chart but does not work. However if I dont have tab it works fine. 

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by jpageacsys** [comment]
I suspect something is going on with the TabView since my app has lots of cartesian charts inside multiple tabs and I've never had any issues. Could you place another dummy control like a button next to it to ensure your tab is displaying correctly? Are you setting the content directly, or programmatically? All my tabs are added in the program, and then set to a page that contains a chart.

**Comment by aspeculat0r** [comment]
I am setting up instance of ViewModel inside the page and then binding the data to chart. I have attached the ViewModel and the MainWindow page. This is just test that I built for this issue.
[SampleLoadGrid.zip](https://github.com/beto-rodriguez/LiveCharts2/files/11670882/SampleLoadGrid.zip)

**Comment by jpageacsys** [comment]
I was able to duplicate the issue.
The control is there but the size is too small. Set the width and height of the cart and you can see it. I'm not sure how the size is supposed to work, I have been setting them specifically so I didn't have this issue. I would agree it should work the same whether it is in a tab view or not.

**Comment by beto-rodriguez** [comment]
This seems to be caused because the container treats the children (the chart in this case) different, LiveCharts controls do not have a specific behavior depending on the parent.

I am not completely sure if this is a bug of WinUI, or is this is the intended behavior and there is something missing in our control.

**Comment by aspeculat0r** [comment]
I guess I will use the workaround to set the size. Thank you guys. Much appreciated.

**Comment by aspeculat0r** [comment]
Okay I figured out that you can use DockPanel as parent container and then bind the height of the Tab to the dockpanel and it works great. This avoids setting the height explicitly. I think the bug is in the Winui
