### ISSUE TITLE
Charts not loading on iOS  AvaloniaUI

### ISSUE THREAD

**Issue by MariusMK1** [beto-rodriguez/LiveCharts2#1208]
**Describe the bug**
PieChart and CartesianChart are not loading fully until you brush  thru the screen with your finger. to update the screen and the animations of the charts are not working on iOS using AvaloniaUI .
But everything works fine on Android and Desktop.

**To Reproduce**
Try to load a PieChart with some values bound to the VM and it looks like it starts the animation and get's stuck at the start and after you brush thru the screen it goes to the end of the animation
 
<img width="562" alt="Screenshot 2023-09-02 at 17 36 15" src="https://github.com/beto-rodriguez/LiveCharts2/assets/93864647/1965f4ae-675b-4a33-bf89-1b7848fe681f">

**Expected behavior**
It should load fully with the animation without interacting with the screen

**Screenshots**
On load
<img width="268" alt="Screenshot 2023-09-02 at 17 26 20" src="https://github.com/beto-rodriguez/LiveCharts2/assets/93864647/8ca51e33-ff1d-4a5a-a12b-c8da912ba6e0">

And after interacting with the screen 
<img width="296" alt="Screenshot 2023-09-02 at 17 26 27" src="https://github.com/beto-rodriguez/LiveCharts2/assets/93864647/d2c8c202-8f84-4cb0-8d7c-9b4a3519c1a6">

**Smartphone (please complete the following information):**
 - Any iPhone
 - Any iOS
 - Version AvaloniaUI 11.0.4
 - Version LiveChartsCore.SkiaSharpView.Avalonia 2.0.0-beta.920

**Comment by MariusMK1** [comment]
Hi, any update?

**Comment by beto-rodriguez** [comment]
Hello, I do not think that the issue belongs to LiveCharts, Avalonia is in charge to render thing on the Screen, we are not doing anything special on the iOS view for Avalonia, Avalonia handles that not us.

In the side of LiveCharts, we are just [rendering the charts](https://github.com/beto-rodriguez/LiveCharts2/blob/master/src/skiasharp/LiveChartsCore.SkiaSharp.Avalonia/MotionCanvas.axaml.cs#L143) using an `ICustomDrawOperation`.

I don't discard that the issue is on LiveCharts, but I think that the odds point that the issue is not here, feel free to let me know if find more evidence that the issue belongs to this library.
