### ISSUE TITLE
WPF: Tooltips cannot be customized completely

### ISSUE THREAD

**Issue by network-interface-controller** [beto-rodriguez/LiveCharts2#1217]
**Describe the bug**
1. Displaying ONLY custom text for a data point in a tooltip is not possible anymore, the label and value are always displayed which is especially annoying for multi-value charts:
![grafik](https://github.com/beto-rodriguez/LiveCharts2/assets/118933349/edf10ad6-ae83-4242-af6c-1d8bde3c9033)

2. As a result of the always displayed label custom texts in tooltips may exceed the chart area and are not shown correctly:
![grafik](https://github.com/beto-rodriguez/LiveCharts2/assets/118933349/6f72d591-19ba-47a6-bdee-dd403aff1996)

**To Reproduce**
--> Create charts and work with tooltips

**Expected behavior**
1. The content of tooltips should be completely customizable without any obligatory fields

**Screenshots**
--> See above

**Desktop (please complete the following information):**
 - OS: Windows 10, Version 22H2
 - Browser --> Not applicable; WPF app
 - Version: LiveChartsCore 2.0.0-beta.950, LiveChartsCore.SkiaSharpView.WPF 2.0.0-beta.950
 - Framework: .NET 7.0

**Smartphone (please complete the following information):**
--> NA

**Additional context**
Described behavior did not occur with version 2.0.0-beta.700

**Comment by beto-rodriguez** [comment]
Hello

You can remove it by not setting the `Series,Name` property or explicitly set it to `LiveCharts.IgnoreSeriesName`.

About the overflow, there are multiple improvements on the dev branch, and the next version will handle this better, for more info see #912

Also, when the default tooltip is not enough, you can always create your own:  https://livecharts.dev/docs/WPF/2.0.0-beta.950/samples.general.customTooltips

I will close this for now, since it seems that the question is answered, but feel free to reply if that is not enough, about the overflow, we can track that in the referenced issue.
