### ISSUE TITLE
Labels next to Horizontal Bars

### ISSUE THREAD

**Issue by girlpunk** [beto-rodriguez/LiveCharts2#1324]
**Is your feature request related to a problem? Please describe.**
Is it possible to render series labels to the left of the axis for a horizontal bar chart.

**Describe the solution you'd like**
Essentially looking to build something like this
![image](https://github.com/beto-rodriguez/LiveCharts2/assets/161093/d4e99294-bc9c-4ec3-a5cd-ff5421d3f065)

**Describe alternatives you've considered**
I have tried using DataLabels on the series, however as these are located around the end of the bar, accurate positioning to align all the labels is very difficult (if not impossible). I have also tried using labels on the axis, however this only displays a single label for all the bars.

**Comment by beto-rodriguez** [comment]
Hi

Using the axis labels is the way, I will consider adding an example to the website.

About showing all the labels, you can force the axis to do so, please see the note in yellow in the next article:

https://livecharts.dev/docs/Maui/2.0.0-rc1/samples.bars.basic

I will close this for now since I think that that should be enough, but feel free to reply or create a new issue if you need further assistance.

**Comment by girlpunk** [comment]
Hi,

I have added the axis configuration as shown in yellow, however this shows `0` instead of the expected text ("Last Thing", etc, in the example)
