### ISSUE TITLE
MaxStep on axis

### ISSUE THREAD

**Issue by essenius** [beto-rodriguez/LiveCharts2#136]
**Is your feature request related to a problem? Please describe.**

I'm trying to create charts where it is important that the axis separator lines are drawn at predetermined intervals.
I tried using MinStep for that, but in one of my charts, instead of the 0.2 that I specified it takes 0.5 which is too large.

**Describe the solution you'd like**

Could a MaxStep be introduced? Alternatlvely, is there a way to not let the step be auto-calculated but just take MinStep?

**Comment by beto-rodriguez** [comment]
Fixed with the refenced commit, just notice the advice in the XML description of the property.

> /// Gets or sets whether the axis should use the <see cref="MinStep"/> as the actual step of the axis, if true, the library
/// will not calculate the step of the axis automatically, instead it will use the value in the <see cref="MinStep"/> property.
/// Be careful when setting this property to true, it might cause performance issues if the step is too small for the current
/// data in the chart. Default value is false.
