### ISSUE TITLE
Wrong data presentation if Mapping used

### ISSUE THREAD

**Issue by cpCr4zy** [beto-rodriguez/LiveCharts2#1456]
**Describe the bug**
I want to show a graph with financial data - a candle sticks with High,Low,Open,Close data.
If I use the old way with a collection of FinancialPointI objects then data displayed correctly:
![ok](https://github.com/beto-rodriguez/LiveCharts2/assets/5735197/001746c9-a5ee-4f19-a7b3-f0809f60f5da)

If I use the new way with Mapping property the i see the wrong presentation:
![nok](https://github.com/beto-rodriguez/LiveCharts2/assets/5735197/a236bbf6-b75d-49f1-9f9a-e8c82b62dc08)

**To Reproduce**
Check the attached project
[LiveChartBug.zip](https://github.com/beto-rodriguez/LiveCharts2/files/14451055/LiveChartBug.zip)

**Expected behavior**
The data are displayed correctly

**Desktop (please complete the following information):**
 - OS: Windows 11
 - LiveChart2 Version: v2.0.0-rc2

**Comment by beto-rodriguez** [comment]
Hello and thanks for the issue.

When using DateTime, please also use an `DateTimeAxis`, this is what causes your issue, just let the library know that you are using  DateTime type, so it can handle it for you:

```c#
X = new ICartesianAxis[]
{
    new DateTimeAxis(TimeSpan.FromDays(1), date => date.ToString("dd MMM yyyy"))
};
```

```xml
<lvc:CartesianChart
    Grid.Row="0"
    Series="{Binding Series}"
    XAxes="{Binding X}"
    TooltipPosition="Hidden"
    ZoomMode="X"/>
```

I tested your repo, and this fixed the issue, the thing is that when using a DateTimeAxis, the library can handle the width of the candle bar, otherwise it to thin and we can't see it.

I will close this issue because I think that this fixes the problem, but let me know if there is something where I can help you.
