### ISSUE TITLE
MAUI: VerticalStackLayout hides the chart

### ISSUE THREAD

**Issue by mimeie** [beto-rodriguez/LiveCharts2#1483]
Hi

I have a problem in .NET MAUI (newest version).

This works fine:
`<ScrollView>
    <lvc:CartesianChart x:Name="myChart" />       
</ScrollView>`

this hides the whole chart:
`<VerticalStackLayout>
    <ScrollView>
    <lvc:CartesianChart x:Name="myChart" />         
</ScrollView>
</VerticalStackLayout>`

I cannot find any reason why it is like this. The same happens also in ContentViews.

Thanks for helping.

**Comment by beto-rodriguez** [comment]
Hi, the chart probably has no size.

Because the chart is inside a VerticalStackLayout, you must define the size of the chart so the stack layout can do its job.

Setting the `HeightRequest` property will fix your issue.

<lvc:CartesianChart x:Name="myChart" HeightRequest="300" />

**Comment by davidortinau** [comment]
@mimeie in addition to what @beto-rodriguez posted, if you put a `ScrollView` inside a `VerticalStackLayout` it will probably take up as much space as it can since `VerticalStackLayout` doesn't constrain its children. This is a different behavior from Xamarin.Forms where layouts did extra calculations based on children. 

If you really need a `ScrollView` inside a `VerticalStackLayout` then you must give that `ScrollView` a size.

**Comment by beto-rodriguez** [comment]
I will close this for now @mimeie let me know if there is something I can help with.
