### ISSUE TITLE
Doughnut Chart Center Label

### ISSUE THREAD

**Issue by tuccitj** [beto-rodriguez/LiveCharts2#1524]
**Is your feature request related to a problem? Please describe.**
I would like to display the total/sum of  all values in a series in the center of a doughnut chart. 

**Describe the solution you'd like**
A property on SKPieChart() that allows you set a text value to the center of a chart. Or a way to add to include an element in the PieSeries that is not displayed except for when set to LiveChartsCore.Measure.PolarLabelsPosition.ChartCenter.

**Describe alternatives you've considered**

I tried adding another element to PieSeries[], hiding it in the legend, and making the fill color transparent. Obviously this doesn't work. Setting IsVisible to false makes everything invisible.
 new PieSeries<decimal>
                            {
                                IsVisibleAtLegend = false,
                                // IsVisible = false,
                                Values = new decimal[] { 1811.54m + 600.54m},
                                Name = "Total",
                                InnerRadius = 60,
                                Fill = new SolidColorPaint(SKColors.Transparent),
                                DataLabelsPaint = new SolidColorPaint(SKColors.Black),
                                DataLabelsSize = 12,
                                // DataLabelsPadding = new LiveChartsCore.Drawing.Padding(padding),
                                DataLabelsPosition = LiveChartsCore.Measure.PolarLabelsPosition.ChartCenter,
                                DataLabelsFormatter = point => point.Coordinate.PrimaryValue.ToString("C2")
                            },

**Comment by beto-rodriguez** [comment]
Hello

Sadly, this is not directly supported for now, but we can draw anything on a chart, here is an article where I explain more about this topic:

https://github.com/beto-rodriguez/LiveCharts2/discussions/1586#discussioncomment-10608662

For now this is the only way, but I will consider adding this as a new feature for the library, I will close this for now, because the plan is not to include this feature soon, but feel free to comment on the referenced thread if you need my assistance to build your implementation, or even better, feel free to create a PR with this feature!!
