### ISSUE TITLE
 Radial Area chart in WPF is missing one border line

### ISSUE THREAD

**Issue by CyanWind97** [beto-rodriguez/LiveCharts2#1542]
**Describe the bug**
I use `PolarLineSeries` to plot a Radial Area chart, but when I set the values to an array with a count of only 3 (e.g., `Values = [1, 3, 3]`), it is missing one closing border.

**To Reproduce**

1. Use the example code from the [Radial Area](https://livecharts.dev/docs/WPF/2.0.0-rc2/samples.polar.radialArea) documentation.
2. Set the values to an array with a count of 3, e.g., `Values = [1, 3, 3]`.

**Expected behavior**
The chart should display without any missing borders, even when the values array count is 3.

**Screenshots**
The left image shows the issue with 3 values (missing border), and the right image shows the correct behavior with 4 values.

![image](https://github.com/user-attachments/assets/53a708eb-7ceb-4b96-bfb8-cb2fb1063bea)

**Desktop (please complete the following information):**
- OS: Windows 11

**Comment by beto-rodriguez** [comment]
Hello

Use the `IsClosed` property to indicate if the last segment should be closed, this is because both scenarios are suported:

https://livecharts.dev/docs/Maui/2.0.0-rc2/samples.polar.basic

or:

https://livecharts.dev/docs/Maui/2.0.0-rc2/samples.polar.coordinates

I will close this for now, since it seems that I answered the question, but feel free to reply if there is something else where I can help.
