### ISSUE TITLE
Column/Bars MinWidth

### ISSUE THREAD

**Issue by Tremlton** [beto-rodriguez/LiveCharts2#1546]
**Is your feature request related to a problem? Please describe.**
i want my bars to always have the same width no matter how many bars there are, but there is only a MaxBarWidth Property not a MinWidth

**Describe the solution you'd like**
Any Reasons why did is not implemented yet? or is there already a solution?

**Comment by beto-rodriguez** [comment]
Hi

**Short answer:**
You can achieve what you need with the `MaxBarWidth`, why isn't that enough?
`MinBarWidth` is not supported because it could lead to wrong plots, for example when the chart width is 100, and we have 20 bars with a `MinBarWidth` of 10.

**Long answer:**
https://stackoverflow.com/questions/38731985/how-customize-column-width-in-column-series/38732955#38732955

I will close this for now, but feel free to reply with any opinion.

**Comment by Tremlton** [comment]
When i have 3 charts arranged one below the other then its looks bad when 1 of them as some more bars and thus a smaller bar width. 

I want all the bars to be the same width so its uniform, if the width is not big enough then i would just handle that with a ScrollViewer or with the internal zooming and panning of the live charts.

**Comment by beto-rodriguez** [comment]
@Tremlton in that case you could sync X axis range on the 3 charts, so they always show the same range on all of the charts:

https://livecharts.dev/docs/Maui/2.0.0-rc2/samples.axes.shared

This way all charts will show the same range on the X axis, and bars will be aligned.
