### ISSUE TITLE
[Feature Request] Export Chart to PDF or Images

### ISSUE THREAD

**Issue by ghost1372** [beto-rodriguez/LiveCharts2#16]
It would be great if an API could be created to Export the chart to PDF or Images (Png, Jpg)

**Comment by beto-rodriguez** [comment]
Luckily for us, SkiaSharp offers a method to create PDFs, I will for sure try to implement this, I think it will be easy.

https://github.com/mono/SkiaSharp/blob/main/samples/Gallery/Shared/Samples/CreatePdfSample.cs

**Comment by WiproSarthak** [comment]
Skiasharp also allows to take snapshot of any SKCanvas view so png and jpg is also possible

https://docs.microsoft.com/en-us/dotnet/api/skiasharp.sksurface.snapshot?view=skiasharp-2.80.2

**Comment by beto-rodriguez** [comment]
Fixed with #80 

The API is the same for all the platforms, but you can find a specific sample for each platform:

[Avalonia](https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/AvaloniaSample/General/ChartToImage/View.axaml.cs)

[Avalonia](https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/AvaloniaSample/General/ChartToImage/View.axaml.cs)

[Avalonia](https://github.com/beto-rodriguez/LiveCharts2/blob/master/samples/AvaloniaSample/General/ChartToImage/View.axaml.cs)
