### ISSUE TITLE
libSkiasharp dll not found

### ISSUE THREAD

**Issue by mpiffari** [beto-rodriguez/LiveCharts2#1624]
**Describe the bug**
After launching WinForms app, I got a not found exception and the live chart UI components get not loaded (with a red cross on it).
 
**To Reproduce**
Create a project and an installer with a WinForm .NET Framework 4.8
**Expected behavior**

**Screenshots**
System.DllNotFoundException: Unable to load library 'libSkiaSharp'.
   in SkiaSharp.LibraryLoader.LoadLocalLibrary[T](String libraryName)
   in SkiaSharp.SkiaApi.<>c.<.cctor>b__1831_0()
   in System.Lazy`1.CreateValue()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Lazy`1.get_Value()
   in SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   in SkiaSharp.SKImageInfo..cctor()

Any idea on how to solve it?

**Comment by beto-rodriguez** [comment]
Hello

The library uses SkiaSharp to render the plot, so probably you are missing the Skia binaries in your installer, I think that you can find more help in the SkiaSharp, this issue might help you:

https://github.com/mono/SkiaSharp/issues/2758

**Comment by mpiffari** [comment]
Did you manage to solve the issue in some way?
I've tried to include manually in the application folder the libskiasharp.dll file, but the error is still present.

**Comment by mpiffari** [comment]
@beto-rodriguez 
I managed to solve this issue, adding manually libskiasharp.dll and libHarfBuzzSharp.dll.
I obtained this file from bin folder of winform project.

What helped me to solve the issue, was this comment: https://github.com/mono/SkiaSharp/issues/572#issuecomment-637522844

**Comment by FuckAllJews** [comment]
@mpiffari I think you have the same problem as me, and I spent more than an hour to figure out why I got this error. When I was developing a Winform application for .NET Framework 4.8 in Microsoft Visual Stadio 2022, I tried to drag FormsPlot from the toolbox to the designer interface, but failed because the error message was: 
"System.DllNotFoundException: Unable to load library 'libSkiaSharp'. 
in SkiaSharp.LibraryLoader.LoadLocalLibrary[T](String libraryName)". 
Looking at the source code of SkiaSharp, I found that the above method is triggered when FromsPlot is instantiated. The Visual Stadio process directory does not contain the "libSkiaSharp.dll" file dependency. So just copy "libSkiaSharp.dll" to the working directory of Visual Stadio and restart Visual Stadio.
