### ISSUE TITLE
hope to support .net8.0

### ISSUE THREAD

**Issue by lindadamama** [beto-rodriguez/LiveCharts2#1678]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Package 'SkiaSharp.Views.WPF 3.0.0-preview.4.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0-windows7.0'. This package may not be fully compatible with your project.

**Comment by nico81cn** [comment]
(same thing on .NET 9 rc2)

**Comment by beto-rodriguez** [comment]
Hello this is an issue of SkiaSharp, sadly there is not much this library can do here.

Thew good news is that this warning seems to be gone on SkiaSharp 3, you can add a reference to SkiaSharp 3 previews, and this warning should be gone, you must also use the latest version of LiveCharts in NuGet since that is the only compatible version with SkiaSharp 3.

I will close this for now since this does not belong to this library, but feel free to reply if you need further assistance.
