### ISSUE TITLE
RowSeries doesn't display rows in the correct order (WinUI)

### ISSUE THREAD

**Issue by assassin316** [beto-rodriguez/LiveCharts2#1726]
Suppose we use the following RowSeries:

```cs
public ISeries[] Series { get; set; } = [
    
    new RowSeries<int>
    {
        Values = [8, 12, 25, 43, 23, 4],
        Stroke = null,
        DataLabelsPaint = new SolidColorPaint(new SKColor(0, 128, 0)),
        DataLabelsSize = 14,
        DataLabelsPosition = DataLabelsPosition.Middle,
        Padding = 0
    },
    new RowSeries<int>
    {
        Values = [-4, -6, -15],
        Stroke = null,
        DataLabelsPaint = new SolidColorPaint(new SKColor(128, 0, 0)),
        DataLabelsSize = 14,
        DataLabelsPosition = DataLabelsPosition.Middle,
        Padding = 0
    }
];
```

The data looks wrong, the negative rows should be grouped on the bottom below the positive rows instead of mixed in.  And when they're mixed in, it causes gaps to appear between the positive rows.

![image](https://github.com/user-attachments/assets/3d2be864-c5bb-460e-82ae-3ca298a9575d)

The results should display in the following manner:

![image](https://github.com/user-attachments/assets/cd81fbdd-c284-4f98-b503-eeec486c30b1)

**Comment by beto-rodriguez** [comment]
Hello and thanks for the issue.

I think there is a misunderstanding here, the plot you are getting is correct, the library is drawing the expected result.

The confusion seems to be related on [how mappers work](https://livecharts.dev/docs/Maui/2.0.0-rc4/Overview.Mappers) in the library.

The data in your first series, is mapped to a `X, Y` coordinate, where Y is the value in your array and X is the index of the element in the array, it means that your first array is mapped to the next coordinates:

````c#
Values = [(0,8), (1,12), (2,25), (3,43), (4,23), (5,4)],
```

And your second array:

```c#
Values = [(0,-4), (1,-6), (2,-15)]
```

That is why you get that result, because both the first 3 points share the same X coordinate.

I will close this for now since this is not an issue of the library, but feel free to reply to let me know where the confusion was, or why did you expect that result.
