### ISSUE TITLE
LiveChartsSettings._currentProvider null reference

### ISSUE THREAD

**Issue by fiftin** [beto-rodriguez/LiveCharts2#212]
I got the exception in method GetProvider of class LiveChartsSettings: https://github.com/beto-rodriguez/LiveCharts2/blob/5d245783488c4b74c273c3386530c37936f8ad8b/src/LiveChartsCore/Kernel/LiveChartsSettings.cs#L148

I spent a lot of time until found source of error: https://github.com/beto-rodriguez/LiveCharts2/blob/5d245783488c4b74c273c3386530c37936f8ad8b/src/skiasharp/LiveChartsCore.SkiaSharp/ColumnSeries.cs#L89

To reproduce just add CartesianChart to XAML without model and bindings. This is an artificial example, but the resulting exception is confusing.

If you instantiate of ColumnSeries after calling InitializeComponent() of your control or page, you got this exeption.

**Comment by beto-rodriguez** [comment]
Thanks for this report, this issue was present in WinUI.

It should not happen any more, I fixed multiple issues in the WinUI view.

https://github.com/beto-rodriguez/LiveCharts2/commit/c68acddf6ababecd7c3f3eff311b3ca77b6c61b6

I am closing this for now, the fix will be included since beta-80 version.
