### ISSUE TITLE
AxisX range  (MinValue and MaxValue)

### ISSUE THREAD

**Issue by kMOsmane** [beto-rodriguez/LiveCharts2#213]
Hello, I was using theses 2 events in live chart V1, AxOnPreviewRangeChanged and AxOnRangeChanged, to modify the range of my X Axis (min and max), but now I didn't find it in the Livecharts V2 , **so how can I change the min and max value of my X Axis in the new version ?**

thank you.

**Comment by beto-rodriguez** [comment]
You can subscribe to the `PropertyChanged` event in your axis, just check when the property name is `MaxLimit ` or `MinLimit `.

You can also set any of these properties to the value you require in your chart, take a look at the docs:

https://github.com/beto-rodriguez/LiveCharts2/blob/master/docs/components/1.7.axes.md#maxlimit-and-minlimit-properties

I will close this for now since it seems enough, please fell free to let me know if there is something missing in my answer.
