### ISSUE TITLE
InvalidOperationException thrown by DataFactory

### ISSUE THREAD

**Issue by Maximilian-Renner** [beto-rodriguez/LiveCharts2#383]
**Describe the bug**
If you rapidly update a cartesian line series using an ObservableCollection, you will encounter random InvalidOperationExceptions which will probably crash your app. This is due to the Fetch method of the DataFactory.cs which is using an enumerator on the given series collection. If the collection does change (e.g. new data point added), an exception will occur.
This bug does not occur if you set a new collection to the "Values" property of the series containing the updated values. It does only occur if you set the collection once and modify it.

**To Reproduce**
1. Clone my demo project which I've provided in the branch "DEBUG_WPF" on my cloned repo: https://github.com/Maximilian-Renner/LiveCharts2/tree/DEBUG_WPF
2. Start the WPF sample project and choose the first example "Test/HighPerformanceTest"
3. Press "Start" button on the top and wait max. 30 seconds until an InvalidOperationException does occur.
4. Go to DataFactory.cs and uncomment code lines 107 to 140 and comment out lines 143 to 153 to apply my suggested fix
5. Start wpf sample project again, no exception will occur

**Expected behavior**
I would expect some kind of synchronization to prevent such issues. As this is possibly to time consuming, I came with this solution.

**Desktop (please complete the following information):**
 - OS: Windows 10 (latest)

**Comment by beto-rodriguez** [comment]
Hi @Maximilian-Renner 

Thanks for the sample, this needs more documentation I will keep an eye on that since it is a common problem.

Notice that the library provides a way to sync your data, please take a look at this [comment](https://github.com/beto-rodriguez/LiveCharts2/issues/225#issuecomment-1012488255) where I explain more about it, your issue will be gone when you follow any of the provided alternatives.

Notice that your suggested fix is not thread safe, your will also get a similar exception randomly when the position [i] does not longer exist because it was modifier by another thread.

**Comment by Maximilian-Renner** [comment]
Hi @beto-rodriguez,

thank you very much for the link. I know that this is not a complete solution, it will just hide exceptions if the collection is changed by adding additional data, this code will for sure fail if you remove/update it. The thing that I was looking for was the SyncContext, this is exactly what I want, thanks for that :)

Just as a suggestion, you could catch the InvalidOperationException in this case and return a more meaningful exception message here to give a hint about the SyncContext property of the chart. This possibly could help others stumbling over the same problem.
