### ISSUE TITLE
Customizing area around chart

### ISSUE THREAD

**Issue by LabuzzMichal** [beto-rodriguez/LiveCharts2#44]
In LiveCharts v0 there was a problem with creating a border around chart area which will stay between chart and axes. One could do it using AxisSection but it was rather a hack than real solution. Example from v0 could be visible on screen below:
![image](https://user-images.githubusercontent.com/17740334/119387065-b15bda00-bcc8-11eb-9c0c-5ef44e560307.png)

Is it going to be supported in v2 ? I would love to have possibility to set something like ChartAreaBorder.
Below example from OxyPlot

![image](https://user-images.githubusercontent.com/17740334/119386599-0fd48880-bcc8-11eb-8b2c-100bf659b6c0.png)

Best regards,
Michał

p.s. I am testing nuget package and it works like a charm ! :)

**Comment by beto-rodriguez** [comment]
![image](https://user-images.githubusercontent.com/10853349/120528790-741ada80-c3a1-11eb-9499-44db231ba9cb.png)

I added a sample of this case in the Lines/Area sample for all the platforms, it is similar to your but the colors are inverted, just because that is easier for my samples template project, the white color comes from the background of the chart and the gray from the new property `DrawMarginFrame`

``` c#
public class ViewModel
    {
        public List<ISeries> Series { get; set; } = new List<ISeries>
        {
            new LineSeries<double>
            {
                Values = new List<double> { -2, -1, 3, 5, 3, 4, 6 },
                // Set he Fill property to build an area series
                // by default the series has a fill color based on your app theme
                Fill = new SolidColorPaintTask(SKColors.CornflowerBlue),

                Stroke = null,
                GeometryFill = null,
                GeometryStroke = null
            }
        };

        // Creates a gray background and border in the draw margin.
        public DrawMarginFrame DrawMarginFrame => new DrawMarginFrame
        {
            Fill = new SolidColorPaintTask(new SKColor(220, 220, 220)),
            Stroke = new SolidColorPaintTask(new SKColor(180, 180, 180), 2)
        };
    }
```
<lvc:CartesianChart Series="{Binding Series}" DrawMarginFrame="{Binding DrawMarginFrame}">
    </lvc:CartesianChart>
``` xml

```
