### ISSUE TITLE
[WPF] Columns from ColumnSeries disappear from chart if Y axis is zoomed too much

### ISSUE THREAD

**Issue by LabuzzMichal** [beto-rodriguez/LiveCharts2#46]
User cant set MaxLimit on Y axis below particular level, otherwise columns are not visible.

**Steps to reproduce the behavior:**
1. Add ColumnSeries and Y axis to the chart
```
        public IEnumerable<ISeries> Series { get; set; } = new ObservableCollection<ISeries>
        {
            new ColumnSeries<double>
            {
                
                Values = new ObservableCollection<double> { 5,6,7,8,5,6,7,8 },       
            }
        };

        public List<Axis> YAxes { get; set; } = new List<Axis>
        {
            new Axis
            {
                IsVisible = true,
                MaxLimit = 20,
                MinLimit = 0,
                ShowSeparatorLines = false,

            }
        };
```
2. Add function allowing you to change MaxLimit
```
        public void Zoom()
        {
            YAxes[0].MaxLimit *= 0.8;
        }
```
3. Columns should be visible
![image](https://user-images.githubusercontent.com/17740334/119831361-7ee6f280-befd-11eb-99f2-8a55e944d8dc.png)

4. Call Zoom function several times. Columns shrink and disappear
![image](https://user-images.githubusercontent.com/17740334/119831484-9c1bc100-befd-11eb-8c0d-4ec74e1934bc.png)

**Expected behavior**
Changing MaxLimit should not affect columns visibility

**Desktop (please complete the following information):**
 - OS: Windows 10 PRO
 - Version beta 10 WPF

**Comment by LabuzzMichal** [comment]
@beto-rodriguez did you manage to reproduce this bug ? :)

**Comment by beto-rodriguez** [comment]
Got it with the previous commit, and the will be included in the next release (beta.13)

**Comment by beto-rodriguez** [comment]
I am rolling this fix back, I am now experiencing a bug because of this fix.

This was never a bug, I miss-understood the problem, The library automatically fits the view to the data on your chart.

The problem for you case was that your Y Axis had a limit from 0 to 4, if you look at your data, none of the values were in that range, thus you got that, an that is correct that is what the library should do, if you wanted to preserve the X range, then you must set the X axis limits too.

Notice this huge difference when zooming and panning, in the first image, the library is able to fit the view to the current data.:

Previously: 

![deleteme](https://user-images.githubusercontent.com/10853349/121224606-5d1b3300-c84e-11eb-99b2-182379e916b6.gif)

Now (after 126d232283c5181717180309b1e5b510e1e79485):

![deleteme2](https://user-images.githubusercontent.com/10853349/121224637-63111400-c84e-11eb-8702-47c2d7e2f297.gif)

**Comment by LabuzzMichal** [comment]
Well, I think I didnt desrbice it clear enough. I was talking about situation when you have zooming and panning disabled and you keep MaxLimit on Y axis defined. Its because you want specific Y range.

I have FFT ColumnSeries chart which is updated every 500ms. I keep MaxLimit on Y axis set to 100 because for the most time these values are much lower than 100. But for time to time these values could increase far above 100 but I dont want to change MaxLimit as I dont really care about that kind of artifacts. Its fine for me to see only a piece of a column below 100. But you cant do it before [126d232](https://github.com/beto-rodriguez/LiveCharts2/commit/126d232283c5181717180309b1e5b510e1e79485) because if all columns exceeds MaxLimit then they dissappear from chart, like you can see on my screen

**Comment by beto-rodriguez** [comment]
> Well, I think I didnt desrbice it clear enough. I was talking about situation when you have zooming and panning disabled and you keep MaxLimit on Y axis defined. Its because you want specific Y range.


I Agree, but notice in your image, that the library respects your range in the Y axis, but because you don't have a a range the X axis, then the library is trying to fit the view to the current data, since you have no points in that Y range, then the X axis messes up.

I think that the library should be smarter, and maybe use the previous valid range if the new one is not valid.
