### ISSUE TITLE
CONSIDER adding the strong naming key to your source control system

### ISSUE THREAD

**Issue by AndrewKhloptsau** [beto-rodriguez/LiveCharts2#508]
**Is your feature request related to a problem? Please describe.**
I've tried to build local LiveChart nugets file with my fixes while I'm waiting the new officially release. And I couldn't do it due to this setting:
 
![image](https://user-images.githubusercontent.com/86781681/171620839-a90b3b6a-b758-4986-8179-e90b1feabb3e.png)

So, maybe, could we consider adding the strong naming key to your source control system?
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

**Comment by beto-rodriguez** [comment]
This is strange, where is your fork at? 

This was removed long time ago, try a git pull and maybe this will be gone.

**Comment by beto-rodriguez** [comment]
The library is no longer strong named, I will close this for now, ensure you are using the latest version of the library and you will not face this issue.

**Comment by pkindruk** [comment]
@beto-rodriguez, since strong naming is back. Can we get back to this?

Working on performance fixes recently I faced an issue that I can't build Release configuration due to missing snk file. I replaced it with my own, but this requires `LivechartsCore/AssemblyInfo.cs` modification. Now I have to pay attention not to commit changes to that file every time I do something.
