### ISSUE TITLE
Optional Axis labels alignment

### ISSUE THREAD

**Issue by korneliuscode** [beto-rodriguez/LiveCharts2#518]
Labels on Y axis are centered by default.

It should be possible to chose if the labels should be centered, left-aligned or right-aligned.

If there are longer numbers as values/labels on the y axis it looks weird to have centered numeric values instead of right aligned.

**Comment by beto-rodriguez** [comment]
This is now fixed with the referenced commit.

Axis now have the `Labels alignment` property, the default value is `Auto` and it lets the library decide the alignment based on the axis position, this means that we rarely would need to set this property, by default it will be aligned closes to the chart, but you can also disagree and set your alignment.

By default: 

![image](https://user-images.githubusercontent.com/10853349/179324889-74aff477-56fc-4239-8cee-f92f992de83a.png)

![image](https://user-images.githubusercontent.com/10853349/179324985-5db7dfc1-598d-4cf9-9a6b-9c7e4dd5241a.png)

**Comment by beto-rodriguez** [comment]
This fix was reverted because it introduced a new issue where there are multiple axes enabled.

**Comment by beto-rodriguez** [comment]
Fixed with the referenced commit and will be included in the next version of the library,
