### ISSUE TITLE
[WPF] [PRISM] Loading PRISM module with livecharts ends up with TDrawingContext being not registered

### ISSUE THREAD

**Issue by LabuzzMichal** [beto-rodriguez/LiveCharts2#53]
**Describe the bug**
When I load prism module with livecharts in my prism application I cant use DrawMarginFrame because its throws "TDrawingContext is not registered" exception

**To Reproduce**
1. Create Prism application with at least one module (module A)
2. Add CartesianChart with DrawMarginFrame defined in module A
3. Load module A dynamicaly in application
4. See error "TDrawingContext is not registered"

**Expected behavior**
DrawMarginFrame is possible to use out of the box

**Desktop (please complete the following information):**
 - OS: Windows 10PRO
 - Version: Beta14 WPF

**Additional context**
I am not sure whether its Livecharts or Prism issue but there is a workaround available. Exception is raised because there is not Theme defined so calling 
`LiveChartsSkiaSharp.DefaultPlatformBuilder(LiveChartsCore.LiveCharts.CurrentSettings) `
solves the problem. But why isn't it called when the library is loaded dynamicaly ? 
Nevertheless maybe its worth to add to documentation section about Livecharts Settings ?

Best regards,
Michal

**Comment by mark-monteiro** [comment]
This is also an issue when using the WPF designer. Instantiating an instance of `DrawMarginFrame` with XAML causes this exception to appear in the designer. The workaround above cannot be used to fix the issue in this case.

I have submitted PR #130 to address this

**Comment by beto-rodriguez** [comment]
> But why isn't it called when the library is loaded dynamically ?

It makes sense that the issue was caused because the first element created in your application was an instance of `DrawMarginFrame`, but the library had a bug initializing the default theme theme as explained in #130 and @mark-monteiro  comment.

> Nevertheless maybe its worth to add to documentation section about LiveCharts Settings ?

It was a bug, this should be done automatically by the library, I have not tested that it is fixed for your case, but it makes a lot of sense, please let us know if the issue persists @LabuzzMichal
