### ISSUE TITLE
Ability to plot complex areas on Cartesian Charts 

### ISSUE THREAD

**Issue by tylerhartwig** [beto-rodriguez/LiveCharts2#536]
I think a nice feature would be able to have more complex areas highlighted on Cartesian Charts. Currently you can call out rectangular pieces with sections, or fill into the axis with series. 

For instance here: 
![image](https://user-images.githubusercontent.com/9355929/174941002-757b24e6-6e88-498b-91e8-fb7756ca0734.png)

That is a plot from R. It would be nice however if these could be any user defined shape or geometry. 

I suppose one could use a custom geometry as a single point, but this seems off for the intended purpose. 

Would appreciate any thoughts on this feature.

**Comment by beto-rodriguez** [comment]
This is fixed with the referenced PR and will be included in the next version of the library.

Docs are not ready yet, but this repo contains an example:

https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/ViewModelsSamples/General/VisualElements/ViewModel.cs

![.](https://user-images.githubusercontent.com/10853349/188360837-4df1c828-dc0e-4dd6-a96f-c7804ae8dfee.png)
