### ISSUE TITLE
Assembly Signing - 2.0.0-beta.300

### ISSUE THREAD

**Issue by RhomGit** [beto-rodriguez/LiveCharts2#547]
**Describe the bug**
Could not load file or assembly 'LiveChartsCore' or one of its dependencies. A strongly-named assembly is required.

**Screenshots**
![image](https://user-images.githubusercontent.com/25700833/178093012-2d83ef45-5440-4b3f-b11c-f1d3fe9add6a.png)
![image](https://user-images.githubusercontent.com/25700833/178093019-8bbde844-708e-4922-93c8-9d3fb91fa06e.png)

**Additional context**
Ref: https://github.com/beto-rodriguez/LiveCharts2/issues/273

**Comment by Kevin-Seiden** [comment]
I have the same issue.  The last version to be strong named seems to be beta 100.  I went to try an update my package and could not because of this issue.

**Comment by beto-rodriguez** [comment]
At some point I thought that it made sense for the library to remove the strong names.

But since we are providing a build for net 4.6.2 I think we should keep it to prevent this issue.

So strong name assemblies will be back in the next release with this commit (ebff9fe3bbd4e3c670015808e48d16064dffc726).

Thanks for the report.
