### ISSUE TITLE
I hope the small window will disappear when the mouse leaves the chart

### ISSUE THREAD

**Issue by WhyILoveSpringRoll** [beto-rodriguez/LiveCharts2#575]
The small window will always exist,like thumbtack.

version ：blazor wasm 330
![1](https://user-images.githubusercontent.com/14737143/183330211-4c303dcc-5b5e-405c-b18c-d26d86e5c78f.png)

**Comment by beto-rodriguez** [comment]
Thanks for the report, this is fixed with the referenced commit.

This is probably a Blazor issue (not completely sure) and related to https://github.com/dotnet/aspnetcore/issues/43129

For now changing to the `pointerout` event seems to work for this library, this fix will be included in the next version of the library.
