### ISSUE TITLE
Serialization loop Detection

### ISSUE THREAD

**Issue by gasparevetrano** [beto-rodriguez/LiveCharts2#634]
**Describe the bug**
Inside my program i serialize through json ObservableCollection < ObservablePoint > object type.
Starting from beta.350 (the issue is not present into beta.330), during thr serialization of  ObservableCollection < ObservablePoint > type a loop is detected.  Is not possible to finalize the json collection serialization.

![Capture](https://user-images.githubusercontent.com/84370861/191465719-1af8d2cc-94b7-4a7b-a5b2-7c0702737ffd.PNG)

I tried to disable the loop detection from json serialization option but the program memory increases very fast until crash. 
![Capture2](https://user-images.githubusercontent.com/84370861/191465797-e5e2596c-9911-4ae3-99b5-8a9f77e7b91c.PNG)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report :) .

The referenced commit adds the `JsonIgnore` attribute to the properties that cause the issue, luckily, we can do it because LiveCharts2 uses `System.Text.Json.Serialization` on net 5 and above and `Newtonsoft.Json` in older versions, so this will make things work out of the box.

**This is fixed when:**

1. You serialize LiveCharts data objects using `net5` or above with `System.Text.Json.Serialization` (the recommended serializer, it is the new version of Newtonsoft.Json *-I think-*)
2. You serialize LiveCharts data objects using `net4.x` and `Newtonsoft.Json`.

**This is not working out of the box when**

1. 1. You serialize LiveCharts data objects using `net5` or above with `System.Text.Json.Serialization` (because on net 5 or above we do not have a reference to Newtonsoft.Json).

in this case you might need to create your own DTO and map it to the LiveCharts object.

This will be included in the next version of the library. Thanks again for the report!
