### ISSUE TITLE
Possibility to export really high quality images

### ISSUE THREAD

**Issue by enricobenedos** [beto-rodriguez/LiveCharts2#651]
**Is your feature request related to a problem? Please describe.**
I'm using this library to integrate it with `QuestPDF`. To do that I will use `GetImage()` method in order to obtain an `SKImage` from my chart and draw it to pdf.

I see that the generated image quality is very poor even if I try to save it to disk with `quality:100` before.
Starting from a vectorial concept normally it is possible to export very high quality images.

How can I achieve it here? For compatibility reasons I'm using `beta.80` but think that nothing has been changed regarding this feature.

**Describe the solution you'd like**
An exported image with a real high quality.

![image](https://user-images.githubusercontent.com/12233746/193028213-ab194d08-2479-41ac-bbbb-a1de73c494cb.png)

**Comment by beto-rodriguez** [comment]
Hi and thanks for the issue, I updated the [QuestPDF sample](https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/QuestPDFSample/Program.cs) to get a higher quality image, this sample will be included in the next update to the web site.



You can generate any image size setting the `Width` and `Height` properties, in the following sample I am forcing the image to have a size of 1920 x 300 and using the image inside a QuestPDF document.

```c#
Document.Create(container =>
{
    _ = container.Page(page =>
    {
        page.Size(PageSizes.A4);
        page.Margin(2, Unit.Centimetre);
        page.PageColor(Colors.White);
        page.DefaultTextStyle(x => x.FontSize(20));

        page.Header()
            .Text("Hello PDF!")
            .SemiBold().FontSize(36).FontColor(Colors.Blue.Medium);

        page.Content()
            .PaddingVertical(1, Unit.Centimetre)
            .Column(x =>
            {
                x.Spacing(20);
                x.Item().Text(Placeholders.LoremIpsum());

                var cartesianChart = new SKCartesianChart
                {
                    // set the size of the size of the image here
                    // then it seems that QuestPDF is scaling the given image to your document size.
                    Width = 1920,
                    Height = 300,
                    Series = new ISeries[]
                    {
                        new LineSeries<int> { Values = new int[] { 1, 5, 4, 6 } },
                        new ColumnSeries<int> { Values = new int[] { 4, 8, 2, 4 } }
                    }
                };

                using var chartImage = cartesianChart.GetImage();
                using var data = chartImage.Encode();

                x.Item().Image(data.AsSpan().ToArray());
            });

        page.Footer()
            .AlignCenter()
            .Text(x =>
            {
                x.Span("Page ");
                x.CurrentPageNumber();
            });
    });
})
.GeneratePdf("hello.pdf");
```

I will close this for now, since this seems to be solved, let me know if you face an issue or something is not working properly!

**Comment by enricobenedos** [comment]
Hi @beto-rodriguez , thanks for your time. I already know usage of `Width` and `Height` properties but this involve in an unexpected behaviour.

The problem is that aspect ratio changes and even if the resolution is better (also the image quality), it becomes difficulty to read. Also in our example the resulting image is very difficult to read. 

My question was about keep a correct aspect ratio maintaining a good image quality.

**Comment by beto-rodriguez** [comment]
With the latest version, we can draw directly on the canvas, instead of drawing an image on the canvas (as suggested by QuestPDF) this improves quality drastically.

Sample: https://github.com/beto-rodriguez/LiveCharts2/blob/dev/samples/QuestPDFSample/Program.cs

Result: [hello.pdf](https://github.com/beto-rodriguez/LiveCharts2/files/9737744/hello.pdf)

**Comment by enricobenedos** [comment]
Thank you @beto-rodriguez, this is what I mean!
