### ISSUE TITLE
Idiot proof error when you forget .UseSkiaSharp(true)

### ISSUE THREAD

**Issue by nogginbox** [beto-rodriguez/LiveCharts2#654]
I'd successfuly used LiveCharts 2 in one project and was copy pasting my code into a new project.

It didn't work and my app crashed with an unhandled naviagtion failed exception that had the message:
```
{"Catastrophic failure (0x8000FFFF (E_UNEXPECTED))"}
```
It took me ages (much longer than it should have done) to remember that in my original project I'd also added some code into MauiProgram.cs which was:

```
.UseSkiaSharp(true)
```

With this code in, everything worked fine. I was just wondering if there was a way to detect this PEBKAC and help you out with a more intuative exception.

**Comment by beto-rodriguez** [comment]
This will probably change in a future according to:

https://github.com/dotnet/maui/issues/7258

Sadly, there is not much this library can do if that is a requirement from MAUI. Maybe I could try to hide this, and instead of `UseSkiaSharp(true)` name the method `UseLiveCharts()` (internally it would just call UseSkiaSharp(true)) then I will be able to detect and throw with more useful information.

**Comment by beto-rodriguez** [comment]
I will close this for now since there is not much we can do, but I will surely try to improve this when Maui supports it.
