### ISSUE TITLE
SkiaSharp currently only works on Web Assembly

### ISSUE THREAD

**Issue by charleypeng** [beto-rodriguez/LiveCharts2#716]
Hi, I'm so excited about this program which makes my web life like.
But currently i am porting my blazor app into wpf and maui using webview.,
Is it possible to run livecharts2  in this case? If not, will it be considered as a feature in later release?
Thanks!

**Comment by beto-rodriguez** [comment]
Hello, I am also excited about all this wasm improvements.

The library uses SkiaSharp to render the charts, this means that we depend on SkiaSharp to implement that.

As far as I can see, webview will not be supported (https://github.com/mono/SkiaSharp/issues/1834) but hopefully it will be a workaround, or something we can do to improve that.

I will close this issue for now, since it seems that there is not much we can do here 😢 but we can see SkiaSharp/Microsoft do and then find a solution for this.
