### ISSUE TITLE
Axis x:Bind issues

### ISSUE THREAD

**Issue by pluto-dev** [beto-rodriguez/LiveCharts2#720]
**Describe the bug**
I'll get `Invalid binding assignment : Cannot directly bind type 'LiveChartsCore.SkiaSharpView.Axis[]' to 'System.Collections.Generic.IEnumerable(LiveChartsCore.Kernel.Sketches.ICartesianAxis)'. Use a cast, converter or function binding to change the type` trying following:

XAML:

![image](https://user-images.githubusercontent.com/38720155/198149973-9f8cc5c6-619c-467a-92f4-ea47c686ff3b.png)

ViewModel:

```csharp
    public Axis[] XAxes { get; set; } =
    {
        new()
        {
            Name = "Temperature in °C",
            NamePaint = new SolidColorPaint { Color = SKColors.MediumPurple},
            Labeler = (value) => $"{value}°",
            MinLimit = 0,
            MinStep = 10,

        }
    };
```

**To Reproduce**
1. Create a new WinUi 3 project
2. Add a line chart
3. Customize the X/Y axis in your Viewmodel
4. xBind to property

**Expected behavior**
Same behaviour as I would use Binding

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Win11 22H2
 - WindowsAppSDK 1.1.5
 - LiveCharts2 2.0.0-beta.514
 - CommunityToolkit.MVVM 8.0.0

**Additional context**
The problem is pretty easy to solve by using ICartesianAxis interface for your property. Maybe an update for the documentation is necessary?

**Comment by beto-rodriguez** [comment]
This issue is caused because you are using `x:Bind`, the documentation works because it uses `Binding` instead, for now I will keep the docs as they are, because `ICartesianAxis` does not expose all the properties of the `Axis` class and will probably result in more confusion.

I will close this for now, but I will keep an eye on this, probably in a future version we will improve this.
