### ISSUE TITLE
Y axis labels are going outside chart area when value is 0

### ISSUE THREAD

**Issue by Pastajello** [beto-rodriguez/LiveCharts2#818]
**Describe the bug**
When values on the chart are 0 then the labels on Y axis are going outside the bounds of chart control. This doesnt happen when values are above 0. The chart is being rescaled on value changes.

**To Reproduce**
1. Start the sample solution
2. Tap on button 2 - chart labels look good
3. Tab on button 1 - chart labels are the same size but now go outside the chart

**Expected behavior**
If labels can fit at one time in the chart control they should always fit, not randomly move outside on some values.

**Screenshots**
![Screen Recording 2022-12-14 at 10 04 30](https://user-images.githubusercontent.com/28345098/207553113-a7db12e8-63db-41ff-a2f9-a69756ca0231.gif)

**Smartphone (please complete the following information):**
 - Device: Standard Pixel 2 API 29 emulator
 - Device: iPhone 14 Pro Max - iOS 16.1

**Additional context**

Sample project
https://github.com/Pastajello/livecharts_chart_isse_repo

**Comment by beto-rodriguez** [comment]
Thanks for the issue and the repo.

I took a look to it, and it seems that the issue is already gone in the last version of the library, notice you are using beta.600, this seems to be gone in the latest version of the library, feel free to reply here or open a new issue if this continues.



![sample](https://user-images.githubusercontent.com/10853349/210285296-d18aed4a-2aaa-46f4-b1b4-38af307b1b5c.gif)
