### ISSUE TITLE
Increase line spacing in multiline-tooltips

### ISSUE THREAD

**Issue by network-interface-controller** [beto-rodriguez/LiveCharts2#849]
**Is your feature request related to a problem? Please describe.**
In version 2.0.0-beta.700 of LiveChartsCore.SkiaSharpView.WPF the line spacing for multiline-tooltips has decreased compared to version 2.0.0-beta.516. This makes the reading uncomfortable (see attached screenshot).

**Describe the solution you'd like**
The line spacing should be increased a little to make it easier to read tooltips with several lines of text.

**Describe alternatives you've considered**
I could not find a way to adapt the formatting on my own.

**Additional context**
![grafik](https://user-images.githubusercontent.com/118933349/209466240-20fc4282-c83e-4abe-8253-c45ac803febc.png)

**Comment by beto-rodriguez** [comment]
Thanks for the report, this was fixed in https://github.com/beto-rodriguez/LiveCharts2/pull/1028, algo labels have the `LineHeight` property now, this allows us to customize the space between lines, this will be included in the next version of the library.

![tt](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/2dd18e6c-457a-4432-b7cb-fdfa13a20e5e)
