### ISSUE TITLE
libSkiaSharp.dll gets copied to project folder

### ISSUE THREAD

**Issue by mosBrkr** [beto-rodriguez/LiveCharts2#85]
**Describe the bug**
We use the LiveCharts2 library in a project (let's call it library X) which serves as a library for other projects (project Y).

When we add the library X in project Y the two following files get copied to the project Y folder:

- libSkiaSharp.dll
- libSkiaSharp.dylib

As we have everything under version control we would prefer not to have to add these files there as well.

**To Reproduce**
1. Create a library project (target framework net472)
2. Create a WPF app (target framework v4.8)
3. Add library to WPF app
4. Check the WPF project folder

**Expected behavior**
Mentioned library is contained somewhere in package folder

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by beto-rodriguez** [comment]
This issue belongs to SkiaSharp.Views.WPF/SkiaSharp.Views.WindowsForms when your .Net target framework is `4.x`, install only skia sharp and you will get those files too.

As a workaround for now try to exclude both files using the .gitignore file.

I am investigating, and it seems that #146 is caused because of this.

**Comment by mosBrkr** [comment]
Thanks for the investigation! Unfortunately it doesn't work that way as when checking the source out on another machine (like a buildserver) the DLL is missing and the build is failing.
I will try to search for another option.
