### ISSUE TITLE
ArgumentOutOfRangeException for DateTime labels on Axis is back in b700

### ISSUE THREAD

**Issue by danielgruethling** [beto-rodriguez/LiveCharts2#898]
**Describe the bug**
When setting the Labeler of an Axis to something like this:
![grafik](https://user-images.githubusercontent.com/31628469/213388632-d65600a4-e957-4091-867e-65afbba96036.png)
And having no series in the chart or when the series is empty the application will throw an Exception on launch with:
![grafik](https://user-images.githubusercontent.com/31628469/213388575-6ff19753-8ad7-492b-8ab6-3c43ac20eee7.png)

**To Reproduce**
1. Extract and build this sample repo [LVC_Testproject.zip](https://github.com/beto-rodriguez/LiveCharts2/files/10454934/LVC_Testproject.zip)
2. Launch the application
3. Observe Exception

**Expected behavior**
App will not throw an Exception on launch and show an empty chart.

**Desktop (please complete the following information):**
 - OS: Win10
 - Version: 2.0.0-beta.700

**Additional context**
Related to closed issue #629.

**Comment by danielgruethling** [comment]
Just checked and it does not crash from that exception. But it makes debugging a huge annoyance because it will throw that exception on basically any mouse movement I make on the graph.
The Exception also gets thrown when trying to move a Crosshair to the edge of the labeled Axis or zooming out on it.

**Comment by Oppozyyox** [comment]
I also found today that if you accidentally have a LineSeries<DateTimePoint> containing a DateTimePoint whose value is greater than the MaxLimit of the Y axis, the Labeler function on the X axis will be called an infinite number of times when the chart is drawn, throwing the same ArgumentOutOfRangeException each time.

**Comment by danielgruethling** [comment]
Exception is still present after updating to b701.

**Comment by danielgruethling** [comment]
Exception is still present after updating to b802.

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report.

The issue happens here because there is no data in the chart, there a couple of things you can do to fix this:

1. Handle the overflow:

```
Chart.XAxes = new List<Axis>
            {
                new Axis
                {
                    Labeler = value =>
                    {
                        if (value < 0) value = 0;
                        var d = new DateTime((long)value);
                        return d.ToString("hh:mm:ss");
                    },
                }
            };
```

2. Set the axis bounds while there is no data in the chart:

```
 Chart.XAxes = new List<Axis>
            {
                new Axis
                {
                    MinLimit = DateTime.Now.Ticks,
                    MaxLimit = DateTime.Now.AddDays(1).Ticks
                }
            };
```

When there is data in your chart you can remove the limits by setting the `MinLimit` and `MaxLimit` to `null`.

**Note for future versions**

Since this seems to be a common issue, I will update the docs and add a helper function to handle the range of the DateTime type.

It is also strange that the issue does not happens when you reference the source code, but it does happen when we reference the NuGet distributed assemblies.
