### ISSUE TITLE
NullPointerException on Application Exit

### ISSUE THREAD

**Issue by grigiada** [beto-rodriguez/LiveCharts2#934]
I performed the porting of a huge UWP project with LiveChart in WinUI 3 with LiveCharts2.
I followed your examples and I created all charts in ViewModel. When I perform the Application Exit command I intercept an NullPointerException (from SkiaSharp library).
Is it my fault? How can I solve this problem?

**Comment by torum** [comment]
I have the same issue and wondering the same thing. I get the following exception when I exit [my WinUI3 app](https://github.com/torum/BitWallpaper) **while chart is loading**.

System.NullReferenceException  
  HResult=0x80004003  
  Message=Object reference not set to an instance of an object.  
  Source=SkiaSharp.Views.Windows  
  stack trace:  
   SkiaSharp.Views.Windows.SKXamlCanvas.Invalidate()

It's not a big deal since app would exit anyway but it would be nice to know how to avoid this.

**Comment by beto-rodriguez** [comment]
I have also seen this, it is strange that WinUI disposes the control, but Invalidate method is still running. 

This should be fished with the referenced commit, now the control verifies if the canvas is still loaded in the UI.

This will be included in the next version of the library, thanks for the report!

**Comment by daltzctr** [comment]
Any chance you'd be able to publish a beta release with the fix?

**Comment by beto-rodriguez** [comment]
yes I am planning to release a new version to NuGet, I hope today or tomorrow is ready.
