### ISSUE TITLE
Custom geometry with background display error

### ISSUE THREAD

**Issue by CosineG** [beto-rodriguez/LiveCharts2#940]
**Describe the bug**
There is a problem with the custom geometries. I follow the tutorial [Line Geometries](https://lvcharts.com/docs/WPF/2.0.0-beta.330/samples.lines.custom), override the OnDraw(), to draw a white circle as background before the SVG path is drawn. But when the mouse hovers over the geometry, both the point and the tooltip, the white circle background will cover the SVG path.

**To Reproduce**
1. Follow the tutorial [Line Geometries](https://lvcharts.com/docs/WPF/2.0.0-beta.330/samples.lines.custom) to create custom geometry.
2. Run the program and let the mouse hovers over the custom geometry.

**Expected behavior**
Both the point and the tooltip should display the SVG only or with background behind SVG.

**Screenshots**

https://user-images.githubusercontent.com/33339051/219959167-6f60c6cf-f7e4-4562-9ae8-2f70c590bacc.mp4

**Environment**
 - OS: Windows 10 19045.2604
 - Version: 2.0.0-beta.701

**Comment by beto-rodriguez** [comment]
Hi and thanks for the report, this is already fixed in the dev branch.

The sample in the web site will be updated in the next release, there are multiple improvements here:

https://github.com/beto-rodriguez/LiveCharts2/tree/master/samples/ViewModelsSamples/Lines/Custom

![maaa](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/1b581755-a2d7-407e-9e6e-685bd4227fac)

I will close this for now because I do not exactly remember the commit where this was fixed, but it was!
