### ISSUE TITLE
WPF - Chart not staying within control bounds and is moving around on refresh/render.

### ISSUE THREAD

**Issue by R33D3Y** [beto-rodriguez/LiveCharts2#974]
**Describe the bug**
The chart seems to render in random locations and sometimes the X-axis renders outside the bounds of the control.

**To Reproduce**

MainWindow.xaml:
```
<wpf:CartesianChart Grid.Row="0"
                    x:Name="Chart"
                    TooltipPosition="Hidden"
                    LegendPosition="Hidden"/>

<Button Grid.Row="1"
        Margin="3"
        Content="Update Data"
        Click="ButtonBase_OnClick"/>
```

MainWindow.xaml.cs:
```
private readonly Random _random = new Random();

private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
{
    Update();
}

private void Update()
{
    List<int> dataEnumerable = new List<int> { _random.Next(1000), _random.Next(1000), _random.Next(1000), _random.Next(1000), _random.Next(1000), _random.Next(1000), _random.Next(1000), _random.Next(1000), _random.Next(1000), _random.Next(1000) };

    Chart.Series = Enumerable.Range(0, dataEnumerable.Count)
        .Select(x => new ColumnSeries<ObservableValue>
        {
            Values = new[] { new ObservableValue(dataEnumerable[x]) },
            Name = (x + 1).ToString(),
            MaxBarWidth = 25,
            DataLabelsPaint = new SolidColorPaint(new SKColor(157, 150, 141)),
            DataLabelsPosition = DataLabelsPosition.Bottom,
            DataLabelsFormatter = point => $"{point.Context.Series.Name}"
        })
        .ToArray();

    Chart.XAxes = new[] { new Axis { LabelsPaint = new SolidColorPaint(SKColors.Transparent), Padding = new Padding(0.5f, 0) } };
    Chart.YAxes = new[] { new Axis { IsVisible = false } };
}
```

**Expected behaviour**
The chart stays static, within the bounds of the control.

**Screenshots**
https://user-images.githubusercontent.com/36885186/229755679-dcedaae4-cec8-401d-90d8-29bb7a7420cc.mp4

**Desktop:**
 - OS: Windows - WPF net6.0-windows
 - Version 10.0.17763 Build 17763

**Comment by beto-rodriguez** [comment]
Hello and thanks for the issue.

I think that there is a confusion here because you are explicitly not drawing the axes. If you draw them this is what is happening:

![change](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/2856a0ba-2a7c-4cd0-ae1b-31578b9873f1)

Since your data is random, the library is defining the axes limits for you, this is why is seems that the chart is jumping, but it is just because the data inside of it is different every time it renders, and it is auto calculating the axes bounds for you.

You can disable this behavior by setting the limits by your self, in the sample you provided I will force the Y axes limits, then the library will always start at the same point no matter the data it contains:

```c#
Chart.YAxes = new[] { new Axis { MinLimit = 0, MaxLimit = 1000 } };
```

![change2](https://github.com/beto-rodriguez/LiveCharts2/assets/10853349/9f585885-6c3b-4778-bf9b-a956cc7051fa)

I will close this for now, better docs will come to prevent this confusion.
