### ISSUE TITLE
WinForm - Legend and tooltip goes out of bound/getting cut off on the edge

### ISSUE THREAD

**Issue by dh4618** [beto-rodriguez/LiveCharts2#987]
**Describe the bug**
When there are multiple series being added to the chart, the legend and tool tip get cut off on the edge.

i.e.:
![image](https://user-images.githubusercontent.com/66186773/234218613-c37496c4-c8ce-4f5b-a04d-036797ae2063.png)

Additionally, when legend is put on the side, for example, LegendPosition = Left in this case, while hovering over the right most points the tooltip doesn't show up. 
![image](https://user-images.githubusercontent.com/66186773/234219523-dbdfa6a1-3afc-4517-a8ac-4d83f833af5e.png)

**To Reproduce**
```
var seriesCollection = new ISeries[]
{
new LineSeries<int>
{
Values = new []{ 2, 5, 10, 6, 0 },
Name = "Test 1",

},
new LineSeries<int>
{
Values = new []{ 3, 17, 2, 9, 14 },
Name = "Test 2",

},
new LineSeries<int>
{
Values = new []{ 2, 15, 4, 2, 6 },
Name = "Test 3"
},
new LineSeries<int>
{
Values = new []{ 3, 7, 12, 9, 4 },
Name = "Test 4"
},
new LineSeries<int>
{
Values = new []{ 2, 15, 4, 2, 24 },
Name = "Test 5"
},
new LineSeries<int>
{
Values = new []{ 3, 7, 2, 9, 19 },
Name = "Test 6"
},
new LineSeries<int>
{
Values = new []{ 3, 5, 5, 8, 6 },
Name = "Test 7"
},
new LineSeries<int>
{
Values = new []{ 3, 7, 2, 9, 4 },
Name = "Test 8"
}
};

chartDemo.Series = seriesCollection;
chartDemo.LegendPosition = LiveChartsCore.Measure.LegendPosition.Bottom;
```

**Expected behavior**
Legends wrapped in multiple lines, and tooltip able to float outside of the chart container. (Like the old livecharts!)

**Screenshots**
See above. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Visual Studio 2022 .Net6.0

**Comment by Vasil20Angelov** [comment]
Also the same problem for WPF

**Comment by manokara** [comment]
This is known issue (at least the legend clipping part, see #832) and actually affects all backends because it's down to the layout of the StackPanel visual that is used as both a container for the legends and the legends themselves. There isn't really a workaround other than changing position, but eventually you're also going to run out of vertical space if you have many datasets. The layouting process uses internal classes and variables so the only way to fix this is by forking the repo, which is what I'm trying to do. If I'm successfull, I'll send a PR soon.
